export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const GET_CLIENT = 'GET_CLIENT';
export const ADD_CLIENT = 'ADD_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const DELETE_ALL_CLIENTS_FROM_COHORT = 'DELETE_ALL_CLIENTS_FROM_COHORT';


