# Generated by Django 3.1.7 on 2021-03-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210311_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='client',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='client',
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default='default first name', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='default last name', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
