# Generated by Django 3.1.7 on 2021-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20210329_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(default='none@none.com', max_length=64),
            preserve_default=False,
        ),
    ]
