# Generated by Django 3.1.7 on 2021-03-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
