# Generated by Django 3.1.7 on 2021-04-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_participant_final_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='final_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantf', to='classroom.submission'),
        ),
    ]
