# Generated by Django 3.1.7 on 2021-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20210402_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='competition_no',
            field=models.IntegerField(choices=[(1, 'Competition 1'), (2, 'Competition 2')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='model_type',
            field=models.IntegerField(choices=[(1, 'Logistic Regression'), (2, 'Decision Tree')], default=1),
        ),
    ]
