# Generated by Django 3.1.7 on 2021-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20210402_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='competition_no',
            field=models.IntegerField(blank=True, choices=[(1, 'Competition 1'), (2, 'Competition 2')], null=True),
        ),
    ]
