# Generated by Django 3.1.7 on 2021-04-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0011_auto_20210402_1257'),
        ('classroom', '0012_auto_20210402_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='competition_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_models.competitionmodel'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='competition_no',
            field=models.IntegerField(choices=[(1, 'Competition 1'), (2, 'Competition 2')], default=1),
            preserve_default=False,
        ),
    ]
