# Generated by Django 3.1.7 on 2021-04-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0012_auto_20210403_0827'),
        ('classroom', '0013_auto_20210402_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='train_test_split_comp_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_test_split_comp_1', to='ml_models.traintestsplit'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='train_test_split_comp_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_test_split_comp_2', to='ml_models.traintestsplit'),
        ),
    ]
