# Generated by Django 3.1.7 on 2021-04-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_auto_20210403_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='final_submission',
        ),
        migrations.AddField(
            model_name='participant',
            name='final_submission_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantf1', to='classroom.submission'),
        ),
        migrations.AddField(
            model_name='participant',
            name='final_submission_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantf2', to='classroom.submission'),
        ),
    ]
