# Generated by Django 3.1.7 on 2021-04-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20210403_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classroom.cohort'),
        ),
    ]
