# Generated by Django 3.1.7 on 2021-05-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20210411_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='email',
            new_name='username',
        ),
    ]
