# Generated by Django 3.1.7 on 2021-03-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dectreenode',
            name='parent_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ml_models.dectreenode'),
        ),
        migrations.AlterField(
            model_name='dectreenode',
            name='side',
            field=models.IntegerField(choices=[(0, 'root'), (1, 'left'), (2, 'right'), (3, 'unclassified')]),
        ),
    ]
