# Generated by Django 3.1.6 on 2021-03-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_auto_20210305_2014'),
        ('ml_models', '0002_auto_20210305_1811'),
    ]

    operations = [
    ]
