# Generated by Django 3.1.7 on 2021-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_auto_20210306_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dectreenode',
            name='classification',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dectreenode',
            name='completeness',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dectreenode',
            name='threshold',
            field=models.FloatField(null=True),
        ),
    ]
