# Generated by Django 3.1.7 on 2021-03-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_auto_20210305_2014'),
        ('ml_models', '0004_auto_20210306_2128'),
    ]

    operations = [
    ]
