# Generated by Django 3.1.7 on 2021-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0006_auto_20210311_1546'),
        ('ml_models', '0003_merge_20210305_2149'),
    ]

    operations = [
    ]
