# Generated by Django 3.1.7 on 2021-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0008_auto_20210320_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
