# Generated by Django 3.1.7 on 2021-04-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0013_feature_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='competition_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorings', to='ml_models.competitionmodel'),
        ),
    ]
