# Generated by Django 3.1.7 on 2021-04-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0014_auto_20210411_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoring',
            name='false_negative_rate',
        ),
        migrations.RemoveField(
            model_name='scoring',
            name='false_positive_rate',
        ),
        migrations.RemoveField(
            model_name='scoring',
            name='true_negative_rate',
        ),
        migrations.RemoveField(
            model_name='scoring',
            name='true_positive_rate',
        ),
        migrations.AddField(
            model_name='scoring',
            name='false_negatives',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='false_positives',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='true_negatives',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='true_positives',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
