# Generated by Django 3.1.7 on 2021-04-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0015_auto_20210416_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodel',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='serialization',
            field=models.TextField(),
        ),
    ]
