# Generated by Django 3.1.7 on 2021-04-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0016_auto_20210417_2255'),
        ('ml_models', '0016_competitionmodel_viz'),
    ]

    operations = [
    ]
