# Generated by Django 3.1.7 on 2021-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0017_merge_20210420_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodel',
            name='features',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='competitionmodel',
            name='serialization',
            field=models.CharField(max_length=1024),
        ),
    ]
