# Generated by Django 3.1.7 on 2021-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0019_auto_20210420_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodel',
            name='viz',
            field=models.TextField(null=True),
        ),
    ]
