# Generated by Django 3.2 on 2021-05-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0020_auto_20210420_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodel',
            name='serialization',
            field=models.BinaryField(),
        ),
    ]
